select schema_name 
from information_schema.schemata ;

create schema maternal_health ;

set search_path to maternal_health ;


---- creating consolidated table
CREATE TABLE Consolidated (case_id int PRIMARY KEY,
    age_years_old INT,
    color_ethnicity int,
    hypertension_past_reported BOOLEAN,
    hypertension_past_treatment text,
    diabetes_mellitus_dm_reported BOOLEAN,
    diabetes_mellitus_disease_gap TEXT,
    diabetes_mellitus_treatment TEXT,
    tobacco_use BOOLEAN,
    tobacco_use_in_months TEXT,
    tobacco_quantity_by_day TEXT,
    alcohol_use BOOLEAN,
    alcohol_quantity_milliliters TEXT,
    alcohol_preference TEXT,
    drugs_preference TEXT,
    drugs_years_use TEXT,
    drugs_during_pregnancy TEXT,
    past_newborn_1_weight TEXT,
    gestational_age_past_newborn_1 TEXT,
    past_newborn_2_weight TEXT,
    gestational_age_past_newborn_2 TEXT,
    past_newborn_3_weight TEXT,
    gestational_age_past_newborn_3 TEXT,
    past_newborn_4_weight TEXT,
    gestational_age_past_newborn_4 TEXT, -- the column name changed related to other gestational_age_newborn
    breakfast_meal BOOLEAN,
    morning_snack BOOLEAN,
    lunch_meal BOOLEAN,
    afternoon_snack BOOLEAN,
    meal_dinner BOOLEAN,
    supper_meal BOOLEAN,
    bean BOOLEAN,
    fruits BOOLEAN,
    vegetables BOOLEAN,
    embedded_food BOOLEAN,
    pasta BOOLEAN,
    cookies BOOLEAN,
    right_systolic_blood_pressure TEXT,
    right_diastolic_blood_pressure TEXT,
    left_systolic_blood_pressure TEXT,
    left_diastolic_blood_pressure TEXT,
    periumbilical_subcutanous_fat TEXT,
    periumbilical_visceral_fat TEXT,
    periumbilical_total_fat FLOAT,
    preperitoneal_subcutaneous_fat FLOAT,
    preperitoneal_visceral_fat FLOAT,
    gestational_age_at_inclusion FLOAT,
    fetal_weight_at_ultrasound TEXT,
    weight_fetal_percentile TEXT,
    past_pregnancies_number INT,
    miscarriage INT,
    first_trimester_hematocrit FLOAT,
    second_trimester_hematocrit TEXT,
    third_trimester_hematocrit TEXT,
    firt_trimester_hemoglobin TEXT,
    second_trimester_hemoglobin TEXT,
    third_trimester_hemoglobin TEXT,
    first_tri_fasting_blood_glucose INT,
    second_tri_fasting_blood_glucose TEXT,
    third_tri_fasting_blood_glucose TEXT,
    first_hour_ogtt75_1st_tri TEXT,
    first_hour_ogtt75_2tri TEXT,
    first_hour_ogtt75_3tri TEXT,
    second_hour_ogtt75_1tri TEXT,
    second_hour_ogtt75_2tri TEXT,
    second_hour_ogtt75_3tri TEXT,
    hiv_1tri TEXT,
    syphilis_1tri TEXT,
    c_hepatitis_1tri TEXT,
    prepregnant_weight TEXT,
    prepregnant_bmi TEXT,
    bmi_according_who TEXT,
    current_maternal_weight_1st_tri TEXT,
    current_maternal_weight_2nd_tri TEXT,
    current_maternal_weight_3rd_tri TEXT,
    maternal_weight_at_inclusion FLOAT,
    hight_at_inclusion FLOAT,
    current_bmi FLOAT,
    current_bmi_according_who INT,
    ultrasound_gestational_age FLOAT,
    maternal_brachial_circumference FLOAT,
    circumference_maternal_calf FLOAT,
    maternal_neck_circumference FLOAT,
    maternal_hip_circumference FLOAT,
    maternal_waist_circumference FLOAT,
    mean_tricciptal_skinfold FLOAT,
    mean_subscapular_skinfold FLOAT,
    mean_supra_iliac_skin_fold FLOAT,
    gestational_age_at_birth FLOAT,
    prepartum_maternal_weight TEXT,
    prepartum_maternal_height TEXT,
    delivery_mode INT,
    cesarean_section_reason TEXT,
    hospital_systolic_blood_pressure TEXT,
    hospital_diastolic_blood_pressure TEXT,
    hospital_hypertension BOOLEAN,
    preeclampsia_record_pregnancy BOOLEAN,
    gestational_diabetes_mellitus BOOLEAN,
    chronic_diabetes TEXT,
    chronic_diseases TEXT,
    disease_diagnose_during_pregnancy TEXT,
    treatment_disease_pregnancy TEXT,
    number_prenatal_appointments INT,
    expected_weight_for_the_newborn TEXT,
    newborn_weight TEXT,
    newborn_height TEXT,
    newborn_head_circumference TEXT,
    thoracic_perimeter_newborn FLOAT,
    meconium_labor BOOLEAN,
    apgar_1st_min INT,
    apgar_5th_min INT,
    pediatric_resuscitation_maneuvers BOOLEAN,
    newborn_intubation BOOLEAN,
    newborn_airway_aspiration BOOLEAN,
    mothers_hospital_stay INT
);

--- moving data from source file
COPY Consolidated
FROM 'C:\My Data\Numpy Ninja\Power BI Related\Maternal Health\observations (2).csv'
DELIMITER ','
CSV HEADER
QUOTE '"';;


select *
from Consolidated ;


--- creating staging table for transformation
create table staging_table (like Consolidated including all) ;

select *
from staging_table ;

insert into staging_table
select *
from Consolidated ;

-- 1. Creating patient_history table 
CREATE TABLE Patient_history (patient_id int PRIMARY KEY,
    age_years_old INT,
    color_ethnicity int,
    hypertension_past_reported boolean,
    hypertension_past_treatment text,
    diabetes_mellitus_dm_reported boolean,
    diabetes_mellitus_disease_gap TEXT,
    diabetes_mellitus_treatment TEXT,
    tobacco_use boolean,
    tobacco_use_in_months TEXT,
    tobacco_quantity_by_day TEXT,
    alcohol_use boolean,
    alcohol_quantity_milliliters TEXT,
    alcohol_preference TEXT,
    drugs_preference TEXT,
    drugs_years_use TEXT,
    drugs_during_pregnancy TEXT,
    past_newborn_1_weight TEXT,
    gestational_age_past_newborn_1 TEXT,
    past_newborn_2_weight TEXT,
    gestational_age_past_newborn_2 TEXT,
    past_newborn_3_weight TEXT,
    gestational_age_past_newborn_3 TEXT,
    past_newborn_4_weight TEXT,
    gestational_age_past_newborn_4 TEXT,
    past_pregnancies_number INT,
    miscarriage INT,
	chronic_diabetes text,
	chronic_diseases text
);


insert into Patient_history(patient_id,
    age_years_old,
	color_ethnicity,
    hypertension_past_reported,
    hypertension_past_treatment,
    diabetes_mellitus_dm_reported,
    diabetes_mellitus_disease_gap,
    diabetes_mellitus_treatment,
    tobacco_use,
    tobacco_use_in_months,
    tobacco_quantity_by_day,
    alcohol_use,
    alcohol_quantity_milliliters,
    alcohol_preference,
    drugs_preference,
    drugs_years_use,
    drugs_during_pregnancy,
    past_newborn_1_weight,
    gestational_age_past_newborn_1,
    past_newborn_2_weight,
    gestational_age_past_newborn_2,
    past_newborn_3_weight,
    gestational_age_past_newborn_3,
    past_newborn_4_weight,
    gestational_age_past_newborn_4,
    past_pregnancies_number,
    miscarriage,
	chronic_diabetes,
	chronic_diseases)
select c.case_id,
    c.age_years_old,
    c.color_ethnicity,
    c.hypertension_past_reported,
    c.hypertension_past_treatment,
    c.diabetes_mellitus_dm_reported,
    c.diabetes_mellitus_disease_gap,
    c.diabetes_mellitus_treatment,
    c.tobacco_use,
    c.tobacco_use_in_months,
    c.tobacco_quantity_by_day,
    c.alcohol_use,
    c.alcohol_quantity_milliliters,
    c.alcohol_preference,
    c.drugs_preference,
    c.drugs_years_use,
    c.drugs_during_pregnancy,
    c.past_newborn_1_weight,
    c.gestational_age_past_newborn_1,
    c.past_newborn_2_weight,
    c.gestational_age_past_newborn_2,
    c.past_newborn_3_weight,
    c.gestational_age_past_newborn_3,
    c.past_newborn_4_weight,
    c.gestational_age_past_newborn_4,
    c.past_pregnancies_number,
    c.miscarriage,
	c.chronic_diabetes,
	c.chronic_diseases 
	from staging_table c ;


select * from Patient_history ;


--- 2. Creating Test_Results table
create table Test_results(patient_id int PRIMARY KEY,
    right_systolic_blood_pressure TEXT,
    right_diastolic_blood_pressure TEXT,
    left_systolic_blood_pressure TEXT,
    left_diastolic_blood_pressure TEXT,
    first_trimester_hematocrit FLOAT,
    second_trimester_hematocrit TEXT,
    third_trimester_hematocrit TEXT,
    first_trimester_hemoglobin TEXT,
    second_trimester_hemoglobin TEXT,
    third_trimester_hemoglobin TEXT,
    first_tri_fasting_blood_glucose INT,
    second_tri_fasting_blood_glucose TEXT,
    third_tri_fasting_blood_glucose TEXT,
    first_hour_ogtt75_1tri TEXT,
    first_hour_ogtt75_2tri TEXT,
    first_hour_ogtt75_3tri TEXT,
    second_hour_ogtt75_1tri TEXT,
    second_hour_ogtt75_2tri TEXT,
    second_hour_ogtt75_3tri TEXT,
    hiv_1tri TEXT,
    syphilis_1tri TEXT,
    c_hepatitis_1tri TEXT,
	hospital_systolic_blood_pressure TEXT,
    hospital_diastolic_blood_pressure TEXT,
    hospital_hypertension boolean) ;

select * from Test_results ;

insert into Test_results(patient_id,
    right_systolic_blood_pressure,
    right_diastolic_blood_pressure,
    left_systolic_blood_pressure,
    left_diastolic_blood_pressure,
    first_trimester_hematocrit,
    second_trimester_hematocrit,
    third_trimester_hematocrit,
    first_trimester_hemoglobin,
    second_trimester_hemoglobin,
    third_trimester_hemoglobin,
    first_tri_fasting_blood_glucose,
    second_tri_fasting_blood_glucose,
    third_tri_fasting_blood_glucose,
    first_hour_ogtt75_1tri,
    first_hour_ogtt75_2tri,
    first_hour_ogtt75_3tri,
    second_hour_ogtt75_1tri,
    second_hour_ogtt75_2tri,
    second_hour_ogtt75_3tri,
    hiv_1tri,
    syphilis_1tri,
    c_hepatitis_1tri,
	hospital_systolic_blood_pressure,
    hospital_diastolic_blood_pressure,
    hospital_hypertension)
	select c.case_id,
    c.right_systolic_blood_pressure,
    c.right_diastolic_blood_pressure,
    c.left_systolic_blood_pressure,
    c.left_diastolic_blood_pressure,
    c.first_trimester_hematocrit,
    c.second_trimester_hematocrit,
    c.third_trimester_hematocrit,
    c.firt_trimester_hemoglobin,
    c.second_trimester_hemoglobin,
    c.third_trimester_hemoglobin,
    c.first_tri_fasting_blood_glucose,
    c.second_tri_fasting_blood_glucose,
    c.third_tri_fasting_blood_glucose,
    c.first_hour_ogtt75_1st_tri,
    c.first_hour_ogtt75_2tri,
    c.first_hour_ogtt75_3tri,
    c.second_hour_ogtt75_1tri,
    c.second_hour_ogtt75_2tri,
    c.second_hour_ogtt75_3tri,
    c.hiv_1tri,
    c.syphilis_1tri,
    c.c_hepatitis_1tri,
	c.hospital_systolic_blood_pressure,
    c.hospital_diastolic_blood_pressure,
    c.hospital_hypertension
	from staging_table c;

select * from Test_results ;



-- 3. Creating Nutrition table
CREATE TABLE Nutrition (patient_id int PRIMARY KEY,
    breakfast_meal boolean,
    morning_snack boolean,
    lunch_meal boolean,
    afternoon_snack boolean,
    meal_dinner boolean,
    supper_meal boolean,
    bean boolean,
    fruits boolean,
    vegetables boolean,
    embedded_food boolean,
    pasta boolean,
    cookies boolean
);

select * from Nutrition;

insert into Nutrition (patient_id,
	breakfast_meal,
    morning_snack,
    lunch_meal,
    afternoon_snack,
    meal_dinner,
    supper_meal,
    bean,
    fruits,
    vegetables,
    embedded_food,
    pasta,
    cookies
)
select c.case_id,
	c.breakfast_meal,
    c.morning_snack,
    c.lunch_meal,
    c.afternoon_snack,
    c.meal_dinner,
    c.supper_meal,
    c.bean,
    c.fruits,
    c.vegetables,
    c.embedded_food,
    c.pasta,
    c.cookies
	from staging_table c;

select * from Nutrition;


-- 4. Creating Gestational outcomes Table
CREATE TABLE Gestational_outcomes (patient_id int PRIMARY KEY,
    gestational_age_at_inclusion FLOAT,
	fetal_weight_at_ultrasound text,
	weight_fetal_percentile text,
	ultrasound_gestational_age float,
	gestational_age_at_birth FLOAT,
	 delivery_mode INT,
	 cesarean_section_reason TEXT,
	number_prenatal_appointments INT,
    expected_weight_for_the_newborn TEXT,
    newborn_weight TEXT,
    newborn_height TEXT,
    newborn_head_circumference TEXT,
    thoracic_perimeter_newborn FLOAT,
    meconium_labor Boolean,
    apgar_1st_min INT,
    apgar_5th_min INT,
    pediatric_resuscitation_maneuvers Boolean,
    newborn_intubation Boolean,
    newborn_airway_aspiration Boolean,
    mothers_hospital_stay INT,
	preeclampsia_record_pregnancy Boolean,
    gestational_diabetes_mellitus Boolean,
	disease_diagnose_during_pregnancy text,
	treatment_disease_pregnancy text
);

select * from Gestational_outcomes

insert into Gestational_outcomes (patient_id,
   gestational_age_at_inclusion,
	fetal_weight_at_ultrasound ,
	weight_fetal_percentile,
	ultrasound_gestational_age ,
	gestational_age_at_birth ,
	 delivery_mode ,
	 cesarean_section_reason ,
	number_prenatal_appointments ,
    expected_weight_for_the_newborn ,
    newborn_weight ,
    newborn_height ,
    newborn_head_circumference ,
    thoracic_perimeter_newborn ,
    meconium_labor ,
    apgar_1st_min ,
    apgar_5th_min ,
    pediatric_resuscitation_maneuvers ,
    newborn_intubation ,
    newborn_airway_aspiration ,
    mothers_hospital_stay,
	preeclampsia_record_pregnancy ,
    gestational_diabetes_mellitus ,
	disease_diagnose_during_pregnancy ,
	treatment_disease_pregnancy 
)
select c.case_id,
   c.gestational_age_at_inclusion,
	c.fetal_weight_at_ultrasound ,
	c.weight_fetal_percentile,
	c.ultrasound_gestational_age ,
	c.gestational_age_at_birth ,
	 c.delivery_mode ,
	 c.cesarean_section_reason ,
	c.number_prenatal_appointments ,
    c.expected_weight_for_the_newborn ,
    c.newborn_weight ,
    c.newborn_height ,
    c.newborn_head_circumference ,
    c.thoracic_perimeter_newborn ,
    c.meconium_labor ,
    c.apgar_1st_min ,
    c.apgar_5th_min ,
    c.pediatric_resuscitation_maneuvers ,
    c.newborn_intubation ,
    c.newborn_airway_aspiration ,
    c.mothers_hospital_stay,
	c.preeclampsia_record_pregnancy ,
    c.gestational_diabetes_mellitus ,
	c.disease_diagnose_during_pregnancy ,
	c.treatment_disease_pregnancy 
	from staging_table c;

select * from Gestational_outcomes



-- 5. Creating Maternal_anthropometry Table

CREATE TABLE Maternal_anthropometry (patient_id int PRIMARY KEY,
    periumbilical_subcutanous_fat TEXT,
    periumbilical_visceral_fat TEXT,
    periumbilical_total_fat FLOAT,
    preperitoneal_subcutaneous_fat FLOAT,
    preperitoneal_visceral_fat FLOAT,
    prepregnant_weight TEXT,
    prepregnant_bmi TEXT,
    bmi_according_who TEXT,
    current_maternal_weight_1st_tri TEXT,
    current_maternal_weight_2nd_tri TEXT,
    current_maternal_weight_3rd_tri TEXT,
    maternal_weight_at_inclusion FLOAT,
    height_at_inclusion FLOAT,
    current_bmi FLOAT,
    current_bmi_according_who INT,
    maternal_brachial_circumference FLOAT,
    circumference_maternal_calf FLOAT,
    maternal_neck_circumference FLOAT,
    maternal_hip_circumference FLOAT,
    maternal_waist_circumference FLOAT,
    mean_tricciptal_skinfold FLOAT,
    mean_subscapular_skinfold FLOAT,
    mean_supra_iliac_skin_fold FLOAT,
    prepartum_maternal_weight TEXT,
    prepartum_maternal_height TEXT
    );

select * from Maternal_anthropometry ;

insert into Maternal_anthropometry (patient_id,
    periumbilical_subcutanous_fat,
    periumbilical_visceral_fat,
    periumbilical_total_fat,
    preperitoneal_subcutaneous_fat,
    preperitoneal_visceral_fat,
    prepregnant_weight,
    prepregnant_bmi,
    bmi_according_who,
    current_maternal_weight_1st_tri,
    current_maternal_weight_2nd_tri,
    current_maternal_weight_3rd_tri,
    maternal_weight_at_inclusion,
    height_at_inclusion,
    current_bmi,
    current_bmi_according_who,
    maternal_brachial_circumference,
    circumference_maternal_calf,
    maternal_neck_circumference,
    maternal_hip_circumference,
    maternal_waist_circumference,
    mean_tricciptal_skinfold,
    mean_subscapular_skinfold,
    mean_supra_iliac_skin_fold,
    prepartum_maternal_weight,
    prepartum_maternal_height
    )
	select c.case_id,
    c.periumbilical_subcutanous_fat,
    c.periumbilical_visceral_fat,
    c.periumbilical_total_fat,
    c.preperitoneal_subcutaneous_fat,
    c.preperitoneal_visceral_fat,
    c.prepregnant_weight,
    c.prepregnant_bmi,
    c.bmi_according_who,
    c.current_maternal_weight_1st_tri,
    c.current_maternal_weight_2nd_tri,
    c.current_maternal_weight_3rd_tri,
    c.maternal_weight_at_inclusion,
    c.hight_at_inclusion,
    c.current_bmi,
    c.current_bmi_according_who,
    c.maternal_brachial_circumference,
    c.circumference_maternal_calf,
    c.maternal_neck_circumference,
    c.maternal_hip_circumference,
    c.maternal_waist_circumference,
    c.mean_tricciptal_skinfold,
    c.mean_subscapular_skinfold,
    c.mean_supra_iliac_skin_fold,
    c.prepartum_maternal_weight,
    c.prepartum_maternal_height
	from staging_table c;

select * from Maternal_anthropometry;

